inherit_gem:
  rubocop-lts: config/rubygem_rspec.yml

plugins: rubocop-on-rbs

RBS:
  Enabled: true

Layout/IndentationConsistency:
  Exclude: ['*.md']

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
